### ISSUE TITLE
feat: 프로필 이미지 수정/삭제 API 구현

### ISSUE THREAD

**Issue by heyazoo1007** [DevTraces/BackEnd#110]
## 📌 이슈 내용
> 프로필 수정 API에서 프로필 이미지 수정을 분리할 예정입니다. 
추가로 프로필 이미지 삭제 API도 구현할 예정입니다. 

<br>

## 📝 To-do
- [x] 프로필 수정 API 코드 수정
- [x] 프로필 이미지 수정 API 구현 
- [x] 프로필 이미지 삭제 API 구현
- [x] 테스트코드 작성

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] 유의미한 label을 추가했는가?
