### ISSUE TITLE
fix: 카카오 소셜로그인 코드 수정 

### ISSUE THREAD

**Issue by heyazoo1007** [DevTraces/BackEnd#123]
## 🤷‍♀ 문제 상황
> 카카오 소셜로그인 시 사용자 정보를 nickname으로 식별했는데, 이는 임의로 생성했기에 nickname인 사용자는 없는데, kakaoUserId는 있는 사용자가 있어서 에러가 발생 

<br>

## ✨ 해결 방법
> 카카오에서 받은 nickname을 username으로 사용하기로 했으므로, username으로 사용자 식별 

<br>

## 📝 To-do
- [x] findByNickname -> findByUsername 으로 변경 

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] 유의미한 label을 추가했는가?
