### ISSUE TITLE
fix: 카카오 소셜로그인 후 받은 토큰이 유효하지 않은 문제 해결

### ISSUE THREAD

**Issue by heyazoo1007** [DevTraces/BackEnd#127]
## 🤷‍♀ 문제 상황
> 카카오 소셜로그인 성공 후 받은 액세스 토큰이 정상 작동하지 않고, 401 에러를 발생시키는 문제가 발생했습니다. 

<br>

## ✨ 해결 방법
>  디버깅을 통해 에러가 난 지점을 따라가니, SecurityUser에서 user의 아이디와 비밀번호를 가지고 로직을 진행하는데 소셜 로그인의 경우 비밀번호가 필요없다고 생각해 따로 추가하지 않았습니다. 그래서 회원가입시 임의로 생성한 닉네임 값을 인코딩해서 DB에 저장하는 로직을 추가했습니다. 
임의의 비밀번호를 사용한 이유는 소셜로그인 시 비밀번호를 입력할 필요가 없기 때문입니다. 

<br>

## 📝 To-do
- [x] 소셜 회원가입 시 사용자에 임의의 비밀번호 부여 

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] 유의미한 label을 추가했는가?
