### ISSUE TITLE
feat: 비밀번호 잊었을 때 이메일 인증 후 새 비밀번호 설정 API

### ISSUE THREAD

**Issue by heyazoo1007** [DevTraces/BackEnd#134]
## 📌 이슈 내용
> 인증 이메일 수신 후 이메일 인증 완료와 새로운 비밀번호를 설정하는 API를 구현할 예정입니다. 

<br>

## 📝 To-do
- [ ] 이메일 인증 + 새 비밀번호 설정 API 구현
- [ ] 테스트코드 작성 

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] 유의미한 label을 추가했는가?
