### ISSUE TITLE
feat: 팔로우 취소할 때 관련 알림 삭제 기능 추가 

### ISSUE THREAD

**Issue by heyazoo1007** [DevTraces/BackEnd#142]
## 📌 이슈 내용
> 팔로우 재요청시 이전 팔로우 알림과 중복되는 문제가 발생했습니다. 이를 해결하기 위해 팔로우 취소 발생시 관련 팔로우 알림을 삭제하는 로직을 추가할 예정입니다. 

<br>

## 📝 To-do
- [x] 팔로우 취소에 관련 알림 삭제 로직 추가 

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] 유의미한 label을 추가했는가?
