### ISSUE TITLE
feat: 회원가입시 인증여부 확인 로직 추가 

### ISSUE THREAD

**Issue by heyazoo1007** [DevTraces/BackEnd#147]
## 📌 이슈 내용
> 회원가입 시 이메일 인증 여부를 확인하기 위한 키를 ResponseBody에 추가할 예정입니다. 

<br>

## 📝 To-do
- [x] 이메일 인증코드 확인 API의 ResponseBody 변경 
- [x] 회원가입 API의 ResponseBody 변경 

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] 유의미한 label을 추가했는가?
