### ISSUE TITLE
feat: 회원가입 API 구현

### ISSUE THREAD

**Issue by soeunkk** [DevTraces/BackEnd#16]
## 📌 이슈 내용
> 사용자 정보(이메일, 비밀번호, 유저네임, 닉네임, 프로필 사진, 자기소개)를 받아 회원을 등록하는 API를 개발한다.

<br>

## 📝 To-do
- [ ] 회원가입 Controller, Service 구현
    - [ ] S3 업로더 유틸 함수를 이용하여 프로필 이미지 S3에 등록 및 url로 변환
    - [ ] 비밀번호는 암호화하여 저장
- [ ] 테스트코드 작성

<br>
