### ISSUE TITLE
feat: 해시태그 엔티티 생성 및 해시태그, 이름, 닉네임 검색 API 구현

### ISSUE THREAD

**Issue by gwakjaeha** [DevTraces/BackEnd#25]
## 📌 이슈 내용
- 해시태그, 이름, 닉네임 검색 API 를 구현함.
- 검색시 Elastic search 를 활용하려 했으나 AWS 프리티어 EC2 의 메모리 부족 현상으로 보류함.
- 우선 AWS RDS 를 활용한 방식으로 검색 기능을 구현함.
- 추후 Elasticsearch 와 유사하면서 프리티어 이용이 가능한 AWS OpenSearch 활용에 대해 논의할 예정임.

<br>

## 📝 To-do
- [x] 해시태그 엔티티 생성
- [x] 해시태그 검색 API 구현
- [x] 이름 검색 API 구현
- [x] 닉네임 검색 API 구현
- [x] 테스트코드 작성

<br>
