### ISSUE TITLE
fix: valid 커스텀 어노테이션 작성

### ISSUE THREAD

**Issue by soeunkk** [DevTraces/BackEnd#34]
## 🤷‍♀ 문제 상황
> password, username, nickname, authKey의 작성 규칙을 정했기 떄문에 Request의 유효성 검사에 반영해야 한다.

<br>

## ✨ 해결 방법
> password, username, nickname, authKey에 대한 유효성 검사 어노테이션을 생성하고 이를 각 Request에 적용시킨다.

<br>

## 📝 To-do
- [ ] @Password, PasswordValidation 클래스 작성
    - [ ] `/^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/` : 8자리 이상, 알파벳 1개 이상, 숫자 1개 이상
- [ ] @Username, UsernameValidation 클래스 작성
    - [ ] `/^.{1,30}$/` : 30자 이하 문자
- [ ] @Nickname, NicknameValidation 클래스 작성
    - [ ] `/^[a-zA-Z][a-zA-Z0-9.]{1,30}$/` : 30자 이하, 대소문자로 시작, 대소문자, 숫자, 마침표(.) 허용
- [ ] @AuthKey, AuthKeyValidation 클래스 작성
    - [ ] `/^\d{6}$/` : 6자리 숫자
- [ ] 각 Request에 적용

<br>

## 🤝 관련 이슈
- #5
- #16
- #21
- #27
