### ISSUE TITLE
feat: Jacoco with Github Action

### ISSUE THREAD

**Issue by soeunkk** [DevTraces/BackEnd#35]
## 📌 이슈 내용
> Github Action을 이용하여 깃허브 상에서 빌드 및 테스팅한다. 
Jacoco의 결과 리포트를 통해 테스트 커버리지를 확인한다.
깃허브 상에서 빌드한다는 것은 local이 아닌 외부에서도 실행 가능해야 한다는 의미이므로 배포 환경을 갖추어야 한다.

<br>

## 📝 To-do
- [ ] 개인정보가 노출되지 않도록 주요 키 Github Secret에 등록
- [ ] .github/workflows에 test-coverage.yaml 파일 작성
    - [ ] Secret 환경변수를 통해 배포 환경과 동일하게 프로퍼티 추가/수정
    - [ ] 빌드 및 테스팅
    - [ ] PR시 댓글로 코드 커버리지 레포트 올리기
    - [ ] README에서 코드 커버리지 뱃지 보여주기
