### ISSUE TITLE
fix: CORS 에러 해결을 위한 Access-Control-Allow-Origin 설정 

### ISSUE THREAD

**Issue by heyazoo1007** [DevTraces/BackEnd#37]
## 🤷‍♀ 문제 상황
> FE 측에서 CORS 에러가 발생해 해결하기 위해 Access-Control-Allow-Origin에 관한 설정을 요청해왔습니다. 

<br>

## ✨ 해결 방법
> 해당 문제는 SecurityConfiguration 클래스에서 설정항목을 추가한 뒤 진행하면 될 것 같습니다.  

<br>

## 📝 To-do
- [x] SecurityConfig에서 설정 조건 추가하기 
- [x] 임의의 포트에서도 접근 가능한지 테스트 

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference
1. https://oingdaddy.tistory.com/243

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [ ] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [ ] 관련 issue가 있다면 추가했는가?
- [x] 유의미한 label을 추가했는가?
