### ISSUE TITLE
feat: 스프링 어플리케이션 ec2에 배포 

### ISSUE THREAD

**Issue by heyazoo1007** [DevTraces/BackEnd#40]
## 📌 이슈 내용
> FE의 API 테스트를 위해서 서버를 배포하는 작업을 합니다. 

<br>

## 📝 To-do
- [x] 프로젝트 빌드 후 FilleZillar를 통해서 배포합니다. 

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] 유의미한 label을 추가했는가?
