### ISSUE TITLE
feat: 이메일/닉네임 중복, 비밀번호 변경 API 구현 

### ISSUE THREAD

**Issue by heyazoo1007** [DevTraces/BackEnd#41]
## 📌 이슈 내용
> 사용자의 프로필을 조회하고, 수정하는 기능을 만들 예정입니다. 

<br>

## 📝 To-do
- [x] 이메일 중복 
- [x] 닉네임 중복 
- [x] 비밀번호 변경 
- [x] 테스트코드 작성 

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] 유의미한 label을 추가했는가?
