### ISSUE TITLE
feat: 프로필 조회/수정 API 구현 

### ISSUE THREAD

**Issue by heyazoo1007** [DevTraces/BackEnd#43]
## 📌 이슈 내용
> 사용자의 프로필 조회와 수정 API를 구현할 예정입니다. 

<br>

## 📝 To-do
- [ ] 프로필 조회 API 구현
- [ ] 프로필 수정 API 구현 
- [ ] 테스트 코드 작성 

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] 유의미한 label을 추가했는가?
