### ISSUE TITLE
fix: 로그인 성공시 응답에 사용자 닉네임 추가 

### ISSUE THREAD

**Issue by heyazoo1007** [DevTraces/BackEnd#56]
## 🤷‍♀ 문제 상황
> 사용자의 닉네임을 알 수 있는 API가 없어 닉네임을 알 수 있는 경로가 없음

<br>

## ✨ 해결 방법
> 로그인 성공시 accessToken과 함께 사용자 닉네임도 같이 전달 

<br>

## 📝 To-do
- [x] 응답에 사용자 닉네임 추가 
    - [x] AuthController
    - [x] OAuthController
    - [x] JwtController

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] 유의미한 label을 추가했는가?
