### ISSUE TITLE
fix: 비밀번호 변경 API 함수명 변경 

### ISSUE THREAD

**Issue by heyazoo1007** [DevTraces/BackEnd#58]
## 🤷‍♀ 문제 상황
> merge할 때 conflict 해결하기 위해 코드를 수정했더니 에러가 발생했습니다. 
기존의 함수명(updatePassword() -> setPassword())

<br>

## ✨ 해결 방법
> updatePassword()의 함수명을 setPassword()로 변경해야할 것 같습니다. 

<br>

## 📝 To-do
- [x] Service 클래스에서 함수명을  updatePassword()애서 setPassword()로 변경하기 

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] 유의미한 label을 추가했는가?
