### ISSUE TITLE
feat: 북마크 엔티티 생성 및 API 구현

### ISSUE THREAD

**Issue by gwakjaeha** [DevTraces/BackEnd#6]
## 📌 이슈 내용
> 북마크 엔티티를 생성하고 북마크 CRD 기능을 구현함.

<br>

## 📝 To-do
- [x] 북마크 엔티티 생성
- [x] 북마크 생성
- [x] 북마크 리스트 조회
- [x] 북마크 삭제
- [x] 테스트코드 작성
- [x] 회원 및 게시물 API 완성 후 통합테스트
