### ISSUE TITLE
fix: 카카오 소셜 로그인시 username을 nickname과 동일하게 설정 

### ISSUE THREAD

**Issue by heyazoo1007** [DevTraces/BackEnd#64]
## 🤷‍♀ 문제 상황
> 카카오 소셜 회원가입 시 카카오 서버로부터 username을 받지 않아 username = null 인 문제 발생 

<br>

## ✨ 해결 방법
> 카카오서버로부터 받은 사용자의 nickname을 username에 동일하게 설정 

<br>

## 📝 To-do
- [x] 카카오 소셜 로그인 시 username에 nickname 값 넣기 

</br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] 유의미한 label을 추가했는가?
