### ISSUE TITLE
feat: 프로필 조회 시 팔로우 정보 추가 

### ISSUE THREAD

**Issue by heyazoo1007** [DevTraces/BackEnd#73]
## 📌 이슈 내용
> 프로필 정보에 팔로우 정보를 추가하는 로직을 구현하려 합니다. 

<br>

## 📝 To-do
- [x] 사용자 팔로우/팔로워 수 조회 로직 구현
- [x] 해당 사용자 팔로우하는지 안하는지 boolean 값 반환
- [x] 테스트코드 작성 

<br>

## 🤝 관련 이슈
- #43 

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] 관련 issue가 있다면 추가했는가?
- [x] 유의미한 label을 추가했는가?
