### ISSUE TITLE
fix: 중복 회원가입 시도할 때 예외처리 

### ISSUE THREAD

**Issue by heyazoo1007** [DevTraces/BackEnd#76]
## 🤷‍♀ 문제 상황
> 이미 소셜로그인으로 회원가입을 진행한 사용자 혹은 일반 회원가입 후 중복된 닉네임으로 카카오 회원가입을 하려는 사용자가 회원가입을 시도하려는 경우 500에러가 발생했습니다. 

<br>

## ✨ 해결 방법
> 소셜로그인 실행시 중복된 이메일, 닉네임으로 시도하려는 경우 예외처리 합니다. 

<br>

## 📝 To-do
- [x] 소셜 로그인 시 닉네임 중복확인 
- [x] 소셜 로그인 코드 리팩토링 

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] 관련 issue가 있다면 추가했는가?
- [x] 유의미한 label을 추가했는가?
