### ISSUE TITLE
deploy : CI/CD 설정을 위한 deploy.yaml, appspec.yml 파일 생성

### ISSUE THREAD

**Issue by heyazoo1007** [DevTraces/BackEnd#8]
## 📌 이슈 내용
> 효율적인 개발 진행을 위해 CI/CD를 진행하려합니다. 그래서 관련 설정을 추가하기 위해 deploy.yaml, appspec.yml 파일을 생성하려 합니다. 

<br>

## 📝 To-do
해당 이슈의 완료 조건입니다.
- [x] deploy.yaml 파일 생성 
- [x] appspec.yml 파일 생성 
- [x] ec2에서 배포 확인 
- [ ] ec2 서버 내에서 API 접근 가능한지 확인 

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### Reference
1. https://goodgid.github.io/Github-Action-CI-CD-Workflows/
2. https://goodgid.github.io/Github-Action-CI-CD-CodeDeploy-App-Spec-File/
<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [ ] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [x] reference가 있다면 추가했는가?
- [ ] 관련 issue가 있다면 추가했는가?
- [x] 유의미한 label을 추가했는가?
