### ISSUE TITLE
fix: 회원가입 시 이미지파일 s3에 저장안되는 문제 해결

### ISSUE THREAD

**Issue by heyazoo1007** [DevTraces/BackEnd#89]
## 🤷‍♀ 문제 상황
> 회원가입 시 이미지 파일을 @RequestParam으로 받지 않아 s3에 프로필 이미지가 저장되지 않는 문제가 발생했습니다. 

<br>

## ✨ 해결 방법
> Request dto로 받는 것이 아닌 각 데이터들을 @RequestParam으로 받도록 할 예정입니다. 

<br>

## 📝 To-do
- [x] AuthController, AuthService 수정 

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] 관련 issue가 있다면 추가했는가?
- [x] 유의미한 label을 추가했는가?
