### ISSUE TITLE
fix: 프로필 수정 함수 필드명 수정, @Nullable 제거

### ISSUE THREAD

**Issue by heyazoo1007** [DevTraces/BackEnd#99]
## 🤷‍♀ 문제 상황
> 프로필 수정 시 필드명을 updateXXX로 설정했는데, 이는 이름에 혼동을 주는 문제가 발생했습니다.
클라이언트로부터 수정된 정보와 수정 안 된 정보를 모두 요청받기에 @Nullable이 필요없어졌습니다. 

<br>

## ✨ 해결 방법
> 필드명에 update를 제거했습니다. 
@Nullable을 제거했습니다. 

<br>

## 📝 To-do
- [ ] 필드명 update 제거 
- [ ] @Nullable 제거

### ✅ 체크 리스트
- [x] issue 제목은 유의미한가?
- [x] 유의미한 label을 추가했는가?
